services:
  quickbite-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "15435:5432"
    networks:
      - quickite-network
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    command: ["postgres", "-c", "ssl=off"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  server:
    build:
      context: ../../../  # root folder
      dockerfile: tools/docker/quickbite/Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    image: quickbite-server
    volumes:
      - ../../../coupons:/app/coupons
    networks:
      - quickite-network
    depends_on:
      quickbite-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - QUICKBITE_DB_CONNECTION_STRING=postgres://postgres:postgres@quickbite-db:5432/postgres?sslmode=disable

volumes:
  db:
    driver: local

networks:
  quickite-network:
    driver: bridge
    name: quickite-network
