name: Server CI
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  coverage-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
          cache-dependency-path: go.sum
      - name: Run Coverage Tests
        run: make go-coverage
      - name: Build
        run: make go-build
